<Project>
  <!--
    _InitializeAssemblyVersion is provided by Arcade. It sets the AssemblyVersion and FileVersion
    properties. We depend on this private Arcade target instead of the SDK-defined GetAssemblyVersion
    since the packaging build does not use the .NET SDK.
  -->
  <Target Name="InitializePackageFileVersion"
          BeforeTargets="Build;Pack"
          DependsOnTargets="_InitializeAssemblyVersion" />
</Project>
