config({
    // Qualifier configuration for cross-resolver imports.
    // DScript test runner pips import MSBuild build outputs via the "RuntimeLibs" module.
    // The qualifier must include the MSBuild global properties so that GetProjectOutputsAsync
    // can match project nodes. Keys MUST match the MSBuild resolver's globalProperties
    // exactly (same values) — the graph builder merges qualifier + globalProperties and
    // rejects conflicts. Extra keys not in globalProperties get added as MSBuild global
    // properties during graph construction, which changes project evaluation.
    // TargetFramework is intentionally omitted — it would force single-TFM evaluation.
    qualifiers: {
        defaultQualifier: {
            Configuration: "Debug",
            SkipAsnXmlGeneration: "true",
            NetFrameworkMinimum: "netstandard2.0",
            NetFrameworkCurrent: "net10.0",
            UseLocalTargetingRuntimePack: "false",
            SkipNativePackaging: "true",
        },
    },
    resolvers: [
        // =========================================================================
        // Ninja resolver: native C libraries (System.Native, System.Globalization.Native, etc.)
        //
        // build-bxl.sh runs CMake to generate build.ninja before invoking bxl.
        // The generated build.ninja is idempotent (content-stable across reruns).
        // =========================================================================
        {
            kind: "Ninja",
            moduleName: "NativeLibs",
            root: d`artifacts/obj/native/linux-x64-Debug`,
            // Build all top-level library targets (shared + static)
            targets: [
                "System.Native",
                "System.Native-Static",
                "System.Globalization.Native",
                "System.Globalization.Native-Static",
                "System.IO.Compression.Native",
                "System.IO.Compression.Native-Static",
                "System.IO.Ports.Native",
                "System.IO.Ports.Native-Static",
                "System.Net.Security.Native",
                "System.Net.Security.Native-Static",
                "System.Security.Cryptography.Native.OpenSsl",
                "System.Security.Cryptography.Native.OpenSsl-Static",
            ],
            // Keep the generated JSON graph file for debugging
            keepProjectGraphFile: true,
            // The build commands reference system headers and tools at absolute paths.
            // Untrack these to avoid DFA violations from reads of system-provided files.
            untrackedDirectoryScopes: [
                // System headers (gcc/libc/openssl/icu)
                d`/usr/include`,
                d`/usr/lib`,
                d`/usr/lib64`,
                // GCC internal headers and libraries
                d`/usr/lib/gcc`,
                // Compiler, linker, ar, ranlib, cmake
                d`/usr/bin`,
                // Temporary files created during compilation
                d`/tmp`,
                // /proc and /sys accessed by some tools
                d`/proc`,
                d`/sys`,
                // Dynamic linker cache
                d`/etc`,
            ],
            // Additional output directories beyond the build root where outputs are written
            additionalOutputDirectories: [
                p`artifacts/obj/native/linux-x64-Debug/bin`,
            ],
        },
        {
            kind: "MsBuild",
            root: d`.`,
            moduleName: "RuntimeLibs",
            msBuildRuntime: "DotNetCore",
            // Graph construction uses MSBuild 9.0 (default, compatible with ProjectGraphBuilder net9.0).
            // Pip execution uses MSBuild from .NET 11 SDK (needed for net11.0 target framework).
            msBuildRuntimeLocation: f`/home/sven/.dotnet/sdk/11.0.100-preview.3.26172.108/MSBuild.dll`,
            // MSBuild writes temp files to /tmp/MSBuild* — untrack to avoid DFA violations.
            untrackedDirectoryScopes: [d`/tmp`],
            // Configuration=Debug is set explicitly so that direct ProjectReferences to generator
            // projects (which inherit no Configuration) and eng/generators.targets references
            // (which set SetConfiguration="Configuration=$(LibrariesConfiguration)" = Debug) 
            // resolve to the same MSBuild graph node, avoiding duplicate pips that share obj/ dirs.
            // Skip AsnXml code generation — the .xml.cs files are already checked in and
            // regeneration/touching would cause DFA violations between concurrent inner builds.
            globalProperties: Map.empty<string, string>()
                .add("Configuration", "Debug")
                .add("SkipAsnXmlGeneration", "true")
                // Replace .NET Framework TFM with netstandard2.0 — net462 can't build on Linux
                // (no .NET Framework reference assemblies). Setting to empty string creates
                // empty TFM segments (;;) that break MSBuild's static graph inner builds.
                // Setting to netstandard2.0 instead: all projects already have netstandard2.0
                // in their TargetFrameworks, so the duplicate gets removed by Distinct().
                .add("NetFrameworkMinimum", "netstandard2.0")
                // Same treatment for NetFrameworkCurrent — test projects (TestUtilities) target
                // $(NetFrameworkCurrent)=net481 which can't build on Linux.
                // Using net10.0 (= NetCoreAppMinimum) instead of netstandard2.0 because
                // TestUtilities code uses types not available in netstandard2.0 (ReadOnlySpan,
                // SafeAccessTokenHandle). net10.0 duplicates the existing NetCoreAppMinimum
                // TFM, so MSBuild's Distinct() normalization collapses it to a single build.
                .add("NetFrameworkCurrent", "net10.0")
                // Disable local targeting pack resolution — OOB multi-TFM projects default to
                // UseLocalTargetingRuntimePack=true which resolves framework refs from
                // artifacts/bin/microsoft.netcore.app.ref/ (a build output directory). This causes
                // DFA violations and shared opaque scrubbing deletes the ref assemblies.
                // Setting false makes them use the SDK's targeting pack instead.
                .add("UseLocalTargetingRuntimePack", "false")
                // Skip native packaging project references (System.IO.Ports) — the native .so
                // is already built by the Ninja resolver, and the pkg/ projects are NuGet packaging
                // only. MSBuild's static graph walks BuildReference="false" refs, pulling in
                // NoTargets packaging projects that fail without the full packaging infrastructure.
                .add("SkipNativePackaging", "true"),
            fileNameEntryPoints: [
                // === Tier 0: CoreLib-only facades (single-target) ===
                r`src/libraries/System.Text.Encoding.Extensions/src/System.Text.Encoding.Extensions.csproj`,
                r`src/libraries/System.Numerics.Vectors/src/System.Numerics.Vectors.csproj`,
                r`src/libraries/System.Reflection.Primitives/src/System.Reflection.Primitives.csproj`,
                r`src/libraries/System.Threading.Overlapped/src/System.Threading.Overlapped.csproj`,
                r`src/libraries/System.Diagnostics.Tracing/src/System.Diagnostics.Tracing.csproj`,
                r`src/libraries/System.Diagnostics.Contracts/src/System.Diagnostics.Contracts.csproj`,
                r`src/libraries/System.Threading.Thread/src/System.Threading.Thread.csproj`,
                r`src/libraries/System.Threading.ThreadPool/src/System.Threading.ThreadPool.csproj`,
                r`src/libraries/System.Runtime.Loader/src/System.Runtime.Loader.csproj`,
                r`src/libraries/System.Reflection.Emit.ILGeneration/src/System.Reflection.Emit.ILGeneration.csproj`,
                r`src/libraries/System.Reflection.Emit.Lightweight/src/System.Reflection.Emit.Lightweight.csproj`,
                r`src/libraries/Microsoft.Win32.Primitives/src/Microsoft.Win32.Primitives.csproj`,
                // === Tier 0: CoreLib-only real code (single-target) ===
                r`src/libraries/System.Reflection.TypeExtensions/src/System.Reflection.TypeExtensions.csproj`,
                r`src/libraries/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj`,
                r`src/libraries/System.Threading/src/System.Threading.csproj`,
                r`src/libraries/System.Memory/src/System.Memory.csproj`,
                r`src/libraries/System.Collections/src/System.Collections.csproj`,
                r`src/libraries/System.Private.Uri/src/System.Private.Uri.csproj`,
                // === Tier 1: depends on Tier 0 libraries ===
                r`src/libraries/System.Runtime/src/System.Runtime.csproj`,
                r`src/libraries/System.Collections.Concurrent/src/System.Collections.Concurrent.csproj`,
                r`src/libraries/System.Collections.NonGeneric/src/System.Collections.NonGeneric.csproj`,
                r`src/libraries/System.ComponentModel/src/System.ComponentModel.csproj`,
                r`src/libraries/System.ObjectModel/src/System.ObjectModel.csproj`,
                r`src/libraries/System.Resources.Writer/src/System.Resources.Writer.csproj`,
                r`src/libraries/System.Runtime.CompilerServices.VisualC/src/System.Runtime.CompilerServices.VisualC.csproj`,
                r`src/libraries/System.Runtime.InteropServices/src/System.Runtime.InteropServices.csproj`,
                r`src/libraries/System.Runtime.Numerics/src/System.Runtime.Numerics.csproj`,
                r`src/libraries/System.Runtime.Serialization.Primitives/src/System.Runtime.Serialization.Primitives.csproj`,
                r`src/libraries/System.Security.Claims/src/System.Security.Claims.csproj`,
                r`src/libraries/System.Threading.Tasks.Parallel/src/System.Threading.Tasks.Parallel.csproj`,
                // === Tier 2: depends on Tier 1 libraries ===
                r`src/libraries/System.Linq/src/System.Linq.csproj`,
                r`src/libraries/System.Collections.Specialized/src/System.Collections.Specialized.csproj`,
                r`src/libraries/System.ComponentModel.Primitives/src/System.ComponentModel.Primitives.csproj`,
                r`src/libraries/System.ComponentModel.EventBasedAsync/src/System.ComponentModel.EventBasedAsync.csproj`,
                r`src/libraries/System.Diagnostics.TraceSource/src/System.Diagnostics.TraceSource.csproj`,
                r`src/libraries/System.Net.WebHeaderCollection/src/System.Net.WebHeaderCollection.csproj`,
                r`src/libraries/System.Web.HttpUtility/src/System.Web.HttpUtility.csproj`,
                // === Multi-TFM projects (unlocking blocked single-target deps) ===
                r`src/libraries/System.Collections.Immutable/src/System.Collections.Immutable.csproj`,
                r`src/libraries/System.Reflection.Metadata/src/System.Reflection.Metadata.csproj`,
                r`src/libraries/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj`,
                r`src/libraries/System.Drawing.Primitives/src/System.Drawing.Primitives.csproj`,
                // === Previously-blocked single-target projects (unblocked by multi-TFM deps above) ===
                r`src/libraries/System.Reflection.Emit/src/System.Reflection.Emit.csproj`,
                r`src/libraries/System.Diagnostics.StackTrace/src/System.Diagnostics.StackTrace.csproj`,
                r`src/libraries/System.Text.RegularExpressions/src/System.Text.RegularExpressions.csproj`,
                r`src/libraries/System.Linq.Expressions/src/System.Linq.Expressions.csproj`,
                r`src/libraries/System.Linq.Queryable/src/System.Linq.Queryable.csproj`,
                r`src/libraries/System.Reflection.DispatchProxy/src/System.Reflection.DispatchProxy.csproj`,
                r`src/libraries/System.Linq.Parallel/src/System.Linq.Parallel.csproj`,
                // === Crypto dependency chain ===
                r`src/libraries/System.Formats.Asn1/src/System.Formats.Asn1.csproj`,
                r`src/libraries/System.IO.MemoryMappedFiles/src/System.IO.MemoryMappedFiles.csproj`,
                r`src/libraries/System.Net.Primitives/src/System.Net.Primitives.csproj`,
                r`src/libraries/System.Console/src/System.Console.csproj`,
                r`src/libraries/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj`,
                r`src/libraries/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj`,
                r`src/libraries/System.Net.NameResolution/src/System.Net.NameResolution.csproj`,
                r`src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj`,
                r`src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj`,
                // === Higher-level libraries ===
                r`src/libraries/System.ComponentModel.TypeConverter/src/System.ComponentModel.TypeConverter.csproj`,
                r`src/libraries/System.ComponentModel.Annotations/src/System.ComponentModel.Annotations.csproj`,
                // === Batch 2: leaf/near-leaf multi-TFM projects ===
                r`src/libraries/Microsoft.Bcl.AsyncInterfaces/src/Microsoft.Bcl.AsyncInterfaces.csproj`,
                r`src/libraries/Microsoft.Bcl.Memory/src/Microsoft.Bcl.Memory.csproj`,
                r`src/libraries/Microsoft.Bcl.Numerics/src/Microsoft.Bcl.Numerics.csproj`,
                r`src/libraries/Microsoft.Extensions.Primitives/src/Microsoft.Extensions.Primitives.csproj`,
                r`src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Microsoft.Extensions.FileSystemGlobbing.csproj`,
                r`src/libraries/Microsoft.Win32.SystemEvents/src/Microsoft.Win32.SystemEvents.csproj`,
                r`src/libraries/System.CodeDom/src/System.CodeDom.csproj`,
                r`src/libraries/System.ComponentModel.Composition/src/System.ComponentModel.Composition.csproj`,
                r`src/libraries/System.Composition.AttributedModel/src/System.Composition.AttributedModel.csproj`,
                r`src/libraries/System.Composition.Runtime/src/System.Composition.Runtime.csproj`,
                r`src/libraries/System.Formats.Cbor/src/System.Formats.Cbor.csproj`,
                r`src/libraries/System.IO.Hashing/src/System.IO.Hashing.csproj`,
                r`src/libraries/System.Reflection.Context/src/System.Reflection.Context.csproj`,
                r`src/libraries/System.Security.Cryptography.ProtectedData/src/System.Security.Cryptography.ProtectedData.csproj`,
                r`src/libraries/Microsoft.CSharp/src/Microsoft.CSharp.csproj`,
                // === Batch 2: Tier 1 (deps already built or in Tier 0 above) ===
                r`src/libraries/System.Text.Encodings.Web/src/System.Text.Encodings.Web.csproj`,
                r`src/libraries/System.Text.Encoding.CodePages/src/System.Text.Encoding.CodePages.csproj`,
                r`src/libraries/System.IO.Compression/src/System.IO.Compression.csproj`,
                r`src/libraries/System.IO.Pipelines/src/System.IO.Pipelines.csproj`,
                r`src/libraries/System.IO.FileSystem.DriveInfo/src/System.IO.FileSystem.DriveInfo.csproj`,
                r`src/libraries/System.Formats.Tar/src/System.Formats.Tar.csproj`,
                r`src/libraries/System.Diagnostics.FileVersionInfo/src/System.Diagnostics.FileVersionInfo.csproj`,
                r`src/libraries/System.Formats.Nrbf/src/System.Formats.Nrbf.csproj`,
                r`src/libraries/System.Security.AccessControl/src/System.Security.AccessControl.csproj`,
                r`src/libraries/System.Threading.Channels/src/System.Threading.Channels.csproj`,
                r`src/libraries/System.Threading.Tasks.Dataflow/src/System.Threading.Tasks.Dataflow.csproj`,
                r`src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj`,
                r`src/libraries/Microsoft.Bcl.Cryptography/src/Microsoft.Bcl.Cryptography.csproj`,
                r`src/libraries/System.Reflection.MetadataLoadContext/src/System.Reflection.MetadataLoadContext.csproj`,
                r`src/libraries/System.Composition.Convention/src/System.Composition.Convention.csproj`,
                r`src/libraries/System.Composition.Hosting/src/System.Composition.Hosting.csproj`,
                // === Batch 2: Tier 2 ===
                r`src/libraries/System.IO.Compression.Brotli/src/System.IO.Compression.Brotli.csproj`,
                r`src/libraries/System.IO.Compression.ZipFile/src/System.IO.Compression.ZipFile.csproj`,
                r`src/libraries/System.IO.Pipes/src/System.IO.Pipes.csproj`,
                r`src/libraries/System.IO.FileSystem.AccessControl/src/System.IO.FileSystem.AccessControl.csproj`,
                r`src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj`,
                r`src/libraries/System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj`,
                r`src/libraries/System.Net.Security/src/System.Net.Security.csproj`,
                r`src/libraries/System.Net.WebSockets/src/System.Net.WebSockets.csproj`,
                r`src/libraries/System.Net.WebProxy/src/System.Net.WebProxy.csproj`,
                r`src/libraries/System.Composition.TypedParts/src/System.Composition.TypedParts.csproj`,
                r`src/libraries/System.Security.Cryptography.Pkcs/src/System.Security.Cryptography.Pkcs.csproj`,
                r`src/libraries/System.IO.FileSystem.Watcher/src/System.IO.FileSystem.Watcher.csproj`,
                r`src/libraries/System.Linq.AsyncEnumerable/src/System.Linq.AsyncEnumerable.csproj`,
                r`src/libraries/System.Resources.Extensions/src/System.Resources.Extensions.csproj`,
                // === Batch 3: Major libraries and Microsoft.Extensions.* ecosystem ===
                r`src/libraries/System.Text.Json/src/System.Text.Json.csproj`,
                r`src/libraries/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj`,
                r`src/libraries/System.Diagnostics.TextWriterTraceListener/src/System.Diagnostics.TextWriterTraceListener.csproj`,
                r`src/libraries/System.IO.IsolatedStorage/src/System.IO.IsolatedStorage.csproj`,
                r`src/libraries/System.IO.Packaging/src/System.IO.Packaging.csproj`,
                r`src/libraries/System.IO.Pipes.AccessControl/src/System.IO.Pipes.AccessControl.csproj`,
                // System.IO.Ports — native pkg/ refs skipped via SkipNativePackaging property
                r`src/libraries/System.IO.Ports/src/System.IO.Ports.csproj`,
                r`src/libraries/System.Memory.Data/src/System.Memory.Data.csproj`,
                r`src/libraries/System.Net.Ping/src/System.Net.Ping.csproj`,
                r`src/libraries/System.Net.Quic/src/System.Net.Quic.csproj`,
                r`src/libraries/System.Net.ServerSentEvents/src/System.Net.ServerSentEvents.csproj`,
                r`src/libraries/System.Transactions.Local/src/System.Transactions.Local.csproj`,
                r`src/libraries/System.Threading.RateLimiting/src/System.Threading.RateLimiting.csproj`,
                r`src/libraries/System.Threading.AccessControl/src/System.Threading.AccessControl.csproj`,
                r`src/libraries/System.Runtime.Serialization.Schema/src/System.Runtime.Serialization.Schema.csproj`,
                r`src/libraries/System.Security.Cryptography.Cose/src/System.Security.Cryptography.Cose.csproj`,
                r`src/libraries/System.Security.Cryptography.Xml/src/System.Security.Cryptography.Xml.csproj`,
                r`src/libraries/System.Security.Permissions/src/System.Security.Permissions.csproj`,
                r`src/libraries/System.ServiceModel.Syndication/src/System.ServiceModel.Syndication.csproj`,
                r`src/libraries/System.Speech/src/System.Speech.csproj`,
                r`src/libraries/System.Windows.Extensions/src/System.Windows.Extensions.csproj`,
                r`src/libraries/System.Composition/src/System.Composition.csproj`,
                r`src/libraries/System.ComponentModel.Composition.Registration/src/System.ComponentModel.Composition.Registration.csproj`,
                r`src/libraries/System.Data.Odbc/src/System.Data.Odbc.csproj`,
                // Previously blocked by VersionLessThan crash — fixed by guarding with empty string check
                r`src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj`,
                r`src/libraries/System.Diagnostics.PerformanceCounter/src/System.Diagnostics.PerformanceCounter.csproj`,
                r`src/libraries/System.Configuration.ConfigurationManager/src/System.Configuration.ConfigurationManager.csproj`,
                r`src/libraries/System.Runtime.Caching/src/System.Runtime.Caching.csproj`,
                r`src/libraries/System.Data.OleDb/src/System.Data.OleDb.csproj`,
                r`src/libraries/System.ServiceProcess.ServiceController/src/System.ServiceProcess.ServiceController.csproj`,
                r`src/libraries/System.DirectoryServices.AccountManagement/src/System.DirectoryServices.AccountManagement.csproj`,
                r`src/libraries/System.DirectoryServices/src/System.DirectoryServices.csproj`,
                r`src/libraries/System.DirectoryServices.Protocols/src/System.DirectoryServices.Protocols.csproj`,
                r`src/libraries/System.Management/src/System.Management.csproj`,
                r`src/libraries/Microsoft.Win32.Registry.AccessControl/src/Microsoft.Win32.Registry.AccessControl.csproj`,
                // === Batch 3: Microsoft.Extensions.* ecosystem ===
                r`src/libraries/Microsoft.Bcl.TimeProvider/src/Microsoft.Bcl.TimeProvider.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/Microsoft.Extensions.DependencyInjection.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyInjection/src/Microsoft.Extensions.DependencyInjection.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyModel/src/Microsoft.Extensions.DependencyModel.csproj`,
                r`src/libraries/Microsoft.Extensions.Options/src/Microsoft.Extensions.Options.csproj`,
                r`src/libraries/Microsoft.Extensions.Options.ConfigurationExtensions/src/Microsoft.Extensions.Options.ConfigurationExtensions.csproj`,
                r`src/libraries/Microsoft.Extensions.Options.DataAnnotations/src/Microsoft.Extensions.Options.DataAnnotations.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Abstractions/src/Microsoft.Extensions.Logging.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging/src/Microsoft.Extensions.Logging.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Configuration/src/Microsoft.Extensions.Logging.Configuration.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Console/src/Microsoft.Extensions.Logging.Console.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Debug/src/Microsoft.Extensions.Logging.Debug.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.EventSource/src/Microsoft.Extensions.Logging.EventSource.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.TraceSource/src/Microsoft.Extensions.Logging.TraceSource.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/Microsoft.Extensions.Configuration.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration/src/Microsoft.Extensions.Configuration.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Binder/src/Microsoft.Extensions.Configuration.Binder.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.CommandLine/src/Microsoft.Extensions.Configuration.CommandLine.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/src/Microsoft.Extensions.Configuration.EnvironmentVariables.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Microsoft.Extensions.Configuration.FileExtensions.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Ini/src/Microsoft.Extensions.Configuration.Ini.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Json/src/Microsoft.Extensions.Configuration.Json.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/Microsoft.Extensions.Configuration.UserSecrets.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Xml/src/Microsoft.Extensions.Configuration.Xml.csproj`,
                r`src/libraries/Microsoft.Extensions.FileProviders.Abstractions/src/Microsoft.Extensions.FileProviders.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.FileProviders.Composite/src/Microsoft.Extensions.FileProviders.Composite.csproj`,
                r`src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Microsoft.Extensions.FileProviders.Physical.csproj`,
                r`src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.Caching.Memory/src/Microsoft.Extensions.Caching.Memory.csproj`,
                r`src/libraries/Microsoft.Extensions.Diagnostics.Abstractions/src/Microsoft.Extensions.Diagnostics.Abstractions.csproj`,
                r`src/libraries/Microsoft.Extensions.Diagnostics/src/Microsoft.Extensions.Diagnostics.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/Microsoft.Extensions.Hosting.Abstractions.csproj`,
                // Previously blocked by VersionLessThan crash (transitive via EventLog)
                r`src/libraries/Microsoft.Extensions.Logging.EventLog/src/Microsoft.Extensions.Logging.EventLog.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting/src/Microsoft.Extensions.Hosting.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/Microsoft.Extensions.Hosting.WindowsServices.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting.Systemd/src/Microsoft.Extensions.Hosting.Systemd.csproj`,
                r`src/libraries/Microsoft.Extensions.Http/src/Microsoft.Extensions.Http.csproj`,
                // === Remaining addable projects (no System.Net.Http dependency) ===
                r`src/libraries/System.Net.Http.WinHttpHandler/src/System.Net.Http.WinHttpHandler.csproj`,
                r`src/libraries/System.Runtime.InteropServices.JavaScript/src/System.Runtime.InteropServices.JavaScript.csproj`,
                // === System.Net.Http and dependents ===
                r`src/libraries/System.Net.Http/src/System.Net.Http.csproj`,
                r`src/libraries/System.Net.Http.Json/src/System.Net.Http.Json.csproj`,
                r`src/libraries/System.Net.Requests/src/System.Net.Requests.csproj`,
                r`src/libraries/System.Net.WebClient/src/System.Net.WebClient.csproj`,
                r`src/libraries/System.Net.Mail/src/System.Net.Mail.csproj`,
                r`src/libraries/System.Net.WebSockets.Client/src/System.Net.WebSockets.Client.csproj`,
                r`src/libraries/System.Net.HttpListener/src/System.Net.HttpListener.csproj`,
                // === System.Private.Xml chain (depends on System.Net.Http) ===
                r`src/libraries/System.Private.Xml/src/System.Private.Xml.csproj`,
                r`src/libraries/System.Private.Xml.Linq/src/System.Private.Xml.Linq.csproj`,
                r`src/libraries/System.Xml.ReaderWriter/src/System.Xml.ReaderWriter.csproj`,
                r`src/libraries/System.Xml.XDocument/src/System.Xml.XDocument.csproj`,
                r`src/libraries/System.Xml.XmlSerializer/src/System.Xml.XmlSerializer.csproj`,
                r`src/libraries/System.Xml.XPath/src/System.Xml.XPath.csproj`,
                r`src/libraries/System.Xml.XPath.XDocument/src/System.Xml.XPath.XDocument.csproj`,
                r`src/libraries/System.Data.Common/src/System.Data.Common.csproj`,
                r`src/libraries/System.Private.DataContractSerialization/src/System.Private.DataContractSerialization.csproj`,
                r`src/libraries/System.Runtime.Serialization.Json/src/System.Runtime.Serialization.Json.csproj`,
                r`src/libraries/System.Runtime.Serialization.Xml/src/System.Runtime.Serialization.Xml.csproj`,
                // === Test projects ===
                r`src/libraries/System.Net.WebHeaderCollection/tests/System.Net.WebHeaderCollection.Tests.csproj`,
                r`src/libraries/System.Web.HttpUtility/tests/System.Web.HttpUtility.Tests.csproj`,
                r`src/libraries/System.Net.WebProxy/tests/System.Net.WebProxy.Tests.csproj`,
                r`src/libraries/System.Resources.Writer/tests/System.Resources.Writer.Tests.csproj`,
                r`src/libraries/System.ComponentModel/tests/System.ComponentModel.Tests.csproj`,
                r`src/libraries/System.Collections/tests/System.Collections.Tests.csproj`,
                r`src/libraries/System.Collections.Concurrent/tests/System.Collections.Concurrent.Tests.csproj`,
                r`src/libraries/System.Collections.NonGeneric/tests/System.Collections.NonGeneric.Tests.csproj`,
                r`src/libraries/System.Collections.Specialized/tests/System.Collections.Specialized.Tests.csproj`,
                r`src/libraries/System.Collections.Immutable/tests/System.Collections.Immutable.Tests.csproj`,
                r`src/libraries/System.ComponentModel.Annotations/tests/System.ComponentModel.Annotations.Tests.csproj`,
                r`src/libraries/System.ComponentModel.EventBasedAsync/tests/System.ComponentModel.EventBasedAsync.Tests.csproj`,
                r`src/libraries/System.ComponentModel.Primitives/tests/System.ComponentModel.Primitives.Tests.csproj`,
                r`src/libraries/System.ComponentModel.TypeConverter/tests/System.ComponentModel.TypeConverter.Tests.csproj`,
                r`src/libraries/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Tests.csproj`,
                r`src/libraries/System.ComponentModel.Composition.Registration/tests/System.ComponentModel.Composition.Registration.Tests.csproj`,
                r`src/libraries/System.Composition.AttributedModel/tests/System.Composition.AttributeModel.Tests.csproj`,
                r`src/libraries/System.Composition.Convention/tests/System.Composition.Convention.Tests.csproj`,
                r`src/libraries/System.Composition.Hosting/tests/System.Composition.Hosting.Tests.csproj`,
                r`src/libraries/System.Composition.Runtime/tests/System.Composition.Runtime.Tests.csproj`,
                r`src/libraries/System.Composition/tests/System.Composition.Tests.csproj`,
                r`src/libraries/System.Composition.TypedParts/tests/System.Composition.TypedParts.Tests.csproj`,
                r`src/libraries/System.Console/tests/System.Console.Tests.csproj`,
                r`src/libraries/System.Diagnostics.Contracts/tests/System.Diagnostics.Contracts.Tests.csproj`,
                r`src/libraries/System.Diagnostics.DiagnosticSource/tests/System.Diagnostics.DiagnosticSource.Tests.csproj`,
                r`src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj`,
                r`src/libraries/System.Diagnostics.StackTrace/tests/System.Diagnostics.StackTrace.Tests.csproj`,
                r`src/libraries/System.Diagnostics.TextWriterTraceListener/tests/System.Diagnostics.TextWriterTraceListener.Tests.csproj`,
                r`src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Tests/System.Diagnostics.TraceSource.Tests.csproj`,
                r`src/libraries/System.Diagnostics.Tracing/tests/System.Diagnostics.Tracing.Tests.csproj`,
                r`src/libraries/System.Drawing.Primitives/tests/System.Drawing.Primitives.Tests.csproj`,
                // EXCLUDED: net10.0 inner build fails — test references ValueAsnReader (net11-only API)
                // r`src/libraries/System.Formats.Asn1/tests/System.Formats.Asn1.Tests.csproj`,
                r`src/libraries/System.Formats.Cbor/tests/System.Formats.Cbor.Tests.csproj`,
                r`src/libraries/System.Formats.Nrbf/tests/System.Formats.Nrbf.Tests.csproj`,
                r`src/libraries/System.Formats.Tar/tests/System.Formats.Tar.Tests.csproj`,
                r`src/libraries/System.IO.Compression/tests/System.IO.Compression.Tests.csproj`,
                r`src/libraries/System.IO.Compression.Brotli/tests/System.IO.Compression.Brotli.Tests.csproj`,
                r`src/libraries/System.IO.Compression.ZipFile/tests/System.IO.Compression.ZipFile.Tests.csproj`,
                r`src/libraries/System.IO.FileSystem.AccessControl/tests/System.IO.FileSystem.AccessControl.Tests.csproj`,
                r`src/libraries/System.IO.FileSystem.DriveInfo/tests/System.IO.FileSystem.DriveInfo.Tests.csproj`,
                r`src/libraries/System.IO.FileSystem.Watcher/tests/System.IO.FileSystem.Watcher.Tests.csproj`,
                r`src/libraries/System.IO.Hashing/tests/System.IO.Hashing.Tests.csproj`,
                r`src/libraries/System.IO.IsolatedStorage/tests/System.IO.IsolatedStorage.Tests.csproj`,
                r`src/libraries/System.IO.MemoryMappedFiles/tests/System.IO.MemoryMappedFiles.Tests.csproj`,
                r`src/libraries/System.IO.Packaging/tests/System.IO.Packaging.Tests.csproj`,
                // Skipped: System.IO.Pipelines.Tests — StreamConformanceTests dep not compatible with net10.0
                r`src/libraries/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj`,
                r`src/libraries/System.IO.Pipes.AccessControl/tests/System.IO.Pipes.AccessControl.Tests.csproj`,
                r`src/libraries/System.IO.Ports/tests/System.IO.Ports.Tests.csproj`,
                r`src/libraries/System.Linq/tests/System.Linq.Tests.csproj`,
                r`src/libraries/System.Linq.AsyncEnumerable/tests/System.Linq.AsyncEnumerable.Tests.csproj`,
                r`src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj`,
                r`src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj`,
                r`src/libraries/System.Linq.Queryable/tests/System.Linq.Queryable.Tests.csproj`,
                r`src/libraries/System.Memory/tests/System.Memory.Tests.csproj`,
                r`src/libraries/System.Memory.Data/tests/System.Memory.Data.Tests.csproj`,
                r`src/libraries/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj`,
                r`src/libraries/System.Net.Http.Json/tests/UnitTests/System.Net.Http.Json.Unit.Tests.csproj`,
                r`src/libraries/System.Net.HttpListener/tests/System.Net.HttpListener.Tests.csproj`,
                r`src/libraries/System.Net.Mail/tests/Unit/System.Net.Mail.Unit.Tests.csproj`,
                r`src/libraries/System.Net.NameResolution/tests/FunctionalTests/System.Net.NameResolution.Functional.Tests.csproj`,
                r`src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/System.Net.NetworkInformation.Functional.Tests.csproj`,
                r`src/libraries/System.Net.Ping/tests/FunctionalTests/System.Net.Ping.Functional.Tests.csproj`,
                r`src/libraries/System.Net.Primitives/tests/FunctionalTests/System.Net.Primitives.Functional.Tests.csproj`,
                r`src/libraries/System.Net.Requests/tests/System.Net.Requests.Tests.csproj`,
                r`src/libraries/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj`,
                r`src/libraries/System.Net.ServerSentEvents/tests/System.Net.ServerSentEvents.Tests.csproj`,
                r`src/libraries/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj`,
                r`src/libraries/System.Net.WebClient/tests/System.Net.WebClient.Tests.csproj`,
                r`src/libraries/System.Net.WebSockets/tests/System.Net.WebSockets.Tests.csproj`,
                r`src/libraries/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj`,
                r`src/libraries/System.Numerics.Tensors/tests/System.Numerics.Tensors.Tests.csproj`,
                r`src/libraries/System.Numerics.Vectors/tests/System.Numerics.Vectors.Tests.csproj`,
                r`src/libraries/System.ObjectModel/tests/System.ObjectModel.Tests.csproj`,
                r`src/libraries/System.Private.Uri/tests/FunctionalTests/System.Private.Uri.Functional.Tests.csproj`,
                r`src/libraries/System.Private.Xml/tests/System.Private.Xml.Tests.csproj`,
                r`src/libraries/System.Reflection.Context/tests/System.Reflection.Context.Tests.csproj`,
                r`src/libraries/System.Reflection.DispatchProxy/tests/System.Reflection.DispatchProxy.Tests.csproj`,
                r`src/libraries/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj`,
                r`src/libraries/System.Reflection.Emit.ILGeneration/tests/System.Reflection.Emit.ILGeneration.Tests.csproj`,
                r`src/libraries/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj`,
                r`src/libraries/System.Reflection.Metadata/tests/System.Reflection.Metadata.Tests.csproj`,
                r`src/libraries/System.Reflection.MetadataLoadContext/tests/System.Reflection.MetadataLoadContext.Tests.csproj`,
                r`src/libraries/System.Reflection.TypeExtensions/tests/System.Reflection.TypeExtensions.Tests.csproj`,
                r`src/libraries/System.Resources.Extensions/tests/System.Resources.Extensions.Tests.csproj`,
                r`src/libraries/System.Runtime.CompilerServices.VisualC/tests/System.Runtime.CompilerServices.VisualC.Tests.csproj`,
                r`src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj`,
                r`src/libraries/System.Runtime.Intrinsics/tests/System.Runtime.Intrinsics.Tests.csproj`,
                r`src/libraries/System.Runtime.Numerics/tests/System.Runtime.Numerics.Tests.csproj`,
                r`src/libraries/System.Runtime.Serialization.Formatters/tests/System.Runtime.Serialization.Formatters.Tests.csproj`,
                r`src/libraries/System.Runtime.Serialization.Json/tests/System.Runtime.Serialization.Json.Tests.csproj`,
                r`src/libraries/System.Runtime.Serialization.Primitives/tests/System.Runtime.Serialization.Primitives.Tests.csproj`,
                r`src/libraries/System.Runtime.Serialization.Xml/tests/System.Runtime.Serialization.Xml.Tests.csproj`,
                r`src/libraries/System.Security.AccessControl/tests/System.Security.AccessControl.Tests.csproj`,
                r`src/libraries/System.Security.Claims/tests/System.Security.Claims.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography/tests/System.Security.Cryptography.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography.Cose/tests/System.Security.Cryptography.Cose.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography.Pkcs/tests/System.Security.Cryptography.Pkcs.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography.ProtectedData/tests/System.Security.Cryptography.ProtectedData.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography.Xml/tests/System.Security.Cryptography.Xml.Tests.csproj`,
                r`src/libraries/System.Security.Principal.Windows/tests/System.Security.Principal.Windows.Tests.csproj`,
                r`src/libraries/System.ServiceModel.Syndication/tests/System.ServiceModel.Syndication.Tests.csproj`,
                r`src/libraries/System.Text.Encoding.CodePages/tests/System.Text.Encoding.CodePages.Tests.csproj`,
                r`src/libraries/System.Text.Encoding.Extensions/tests/System.Text.Encoding.Extensions.Tests.csproj`,
                r`src/libraries/System.Text.Encodings.Web/tests/System.Text.Encodings.Web.Tests.csproj`,
                // EXCLUDED: net11.0 pip fails (PascalCase API not in SDK targeting pack),
                // net10.0 pip fails (JsonNamingPolicyAttribute not in net10 targeting pack)
                // r`src/libraries/System.Text.Json/tests/System.Text.Json.Tests/System.Text.Json.Tests.csproj`,
                // EXCLUDED: net10.0 inner build fails — conditional source files exclude both
                // .netfx.cs and .netcoreapp.cs variants for net10.0 TFM
                // r`src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/System.Text.RegularExpressions.Tests.csproj`,
                r`src/libraries/System.Threading/tests/System.Threading.Tests.csproj`,
                r`src/libraries/System.Threading.AccessControl/tests/System.Threading.AccessControl.Tests.csproj`,
                r`src/libraries/System.Threading.Channels/tests/System.Threading.Channels.Tests.csproj`,
                r`src/libraries/System.Threading.Overlapped/tests/System.Threading.Overlapped.Tests.csproj`,
                r`src/libraries/System.Threading.RateLimiting/tests/System.Threading.RateLimiting.Tests.csproj`,
                r`src/libraries/System.Threading.Tasks.Dataflow/tests/System.Threading.Tasks.Dataflow.Tests.csproj`,
                r`src/libraries/System.Threading.Tasks.Parallel/tests/System.Threading.Tasks.Parallel.Tests.csproj`,
                r`src/libraries/System.Threading.Thread/tests/System.Threading.Thread.Tests.csproj`,
                r`src/libraries/System.Threading.ThreadPool/tests/System.Threading.ThreadPool.Tests.csproj`,
                r`src/libraries/System.Transactions.Local/tests/System.Transactions.Local.Tests.csproj`,
                r`src/libraries/System.Data.Common/tests/System.Data.Common.Tests.csproj`,
                r`src/libraries/System.Private.Xml.Linq/tests/misc/System.Xml.Linq.Misc.Tests.csproj`,
                r`src/libraries/Microsoft.Bcl.AsyncInterfaces/tests/Microsoft.Bcl.AsyncInterfaces.Tests.csproj`,
                r`src/libraries/Microsoft.Bcl.Cryptography/tests/Microsoft.Bcl.Cryptography.Tests.csproj`,
                r`src/libraries/Microsoft.Bcl.Memory/tests/Microsoft.Bcl.Memory.Tests.csproj`,
                r`src/libraries/Microsoft.Bcl.Numerics/tests/Microsoft.Bcl.Numerics.Tests.csproj`,
                r`src/libraries/Microsoft.Bcl.TimeProvider/tests/Microsoft.Bcl.TimeProvider.Tests.csproj`,
                r`src/libraries/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Caching.Memory/tests/Microsoft.Extensions.Caching.Memory.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration/tests/Microsoft.Extensions.Configuration.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Binder/tests/UnitTests/Microsoft.Extensions.Configuration.Binder.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.CommandLine/tests/Microsoft.Extensions.Configuration.CommandLine.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/Microsoft.Extensions.Configuration.EnvironmentVariables.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.FileExtensions/tests/Microsoft.Extensions.Configuration.FileExtensions.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Ini/tests/Microsoft.Extensions.Configuration.Ini.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Json/tests/Microsoft.Extensions.Configuration.Json.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.UserSecrets/tests/Microsoft.Extensions.Configuration.UserSecrets.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Configuration.Xml/tests/Microsoft.Extensions.Configuration.Xml.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/Microsoft.Extensions.DependencyInjection.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.DependencyModel/tests/Microsoft.Extensions.DependencyModel.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Diagnostics.Abstractions/tests/Microsoft.Extensions.Diagnostics.Abstractions.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Diagnostics/tests/Microsoft.Extensions.Diagnostics.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.FileProviders.Composite/tests/Microsoft.Extensions.FileProviders.Composite.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/Microsoft.Extensions.FileProviders.Physical.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/Microsoft.Extensions.FileSystemGlobbing.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting.Abstractions/tests/Microsoft.Extensions.Hosting.Abstractions.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Microsoft.Extensions.Hosting.Unit.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Hosting.Systemd/tests/Microsoft.Extensions.Hosting.Systemd.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging/tests/Common/Microsoft.Extensions.Logging.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Abstractions/tests/Microsoft.Extensions.Logging.Generators.Tests/Microsoft.Extensions.Logging.Generators.Roslyn4.8.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/Microsoft.Extensions.Logging.Console.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Logging.EventSource/tests/Microsoft.Extensions.Logging.EventSource.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/Microsoft.Extensions.Options.Tests.csproj`,
                r`src/libraries/Microsoft.Extensions.Primitives/tests/Microsoft.Extensions.Primitives.Tests.csproj`,
                r`src/libraries/Microsoft.Win32.Primitives/tests/Microsoft.Win32.Primitives.Tests.csproj`,
                r`src/libraries/Microsoft.Win32.Registry/tests/Microsoft.Win32.Registry.Tests.csproj`,
                r`src/libraries/Microsoft.Win32.Registry.AccessControl/tests/Microsoft.Win32.Registry.AccessControl.Tests.csproj`,
                r`src/libraries/Microsoft.Win32.SystemEvents/tests/Microsoft.Win32.SystemEvents.Tests.csproj`,
                r`src/libraries/System.CodeDom/tests/System.CodeDom.Tests.csproj`,
                r`src/libraries/System.Configuration.ConfigurationManager/tests/System.Configuration.ConfigurationManager.Tests.csproj`,
                // EXCLUDED: net10.0 inner build fails — Interop types inaccessible on Linux
                // r`src/libraries/System.Data.Odbc/tests/System.Data.Odbc.Tests.csproj`,
                r`src/libraries/System.Data.OleDb/tests/System.Data.OleDb.Tests.csproj`,
                r`src/libraries/System.Diagnostics.EventLog/tests/System.Diagnostics.EventLog.Tests.csproj`,
                // EXCLUDED: net10.0 inner build fails — Windows-only Interop/PerformanceCounterLib types
                // r`src/libraries/System.Diagnostics.PerformanceCounter/tests/System.Diagnostics.PerformanceCounter.Tests.csproj`,
                r`src/libraries/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj`,
                r`src/libraries/System.DirectoryServices/tests/System.DirectoryServices.Tests.csproj`,
                r`src/libraries/System.DirectoryServices.AccountManagement/tests/System.DirectoryServices.AccountManagement.Tests.csproj`,
                r`src/libraries/System.DirectoryServices.Protocols/tests/System.DirectoryServices.Protocols.Tests.csproj`,
                r`src/libraries/System.Management/tests/System.Management.Tests.csproj`,
                r`src/libraries/System.Net.Quic/tests/FunctionalTests/System.Net.Quic.Functional.Tests.csproj`,
                r`src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching.Tests.csproj`,
                r`src/libraries/System.Runtime.Serialization.Schema/tests/System.Runtime.Serialization.Schema.Tests.csproj`,
                r`src/libraries/System.Security.Cryptography.OpenSsl/tests/System.Security.Cryptography.OpenSsl.Tests.csproj`,
                r`src/libraries/System.Security.Permissions/tests/System.Security.Permissions.Tests.csproj`,
                r`src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests.csproj`,
                r`src/libraries/System.Speech/tests/System.Speech.Tests.csproj`,
                r`src/libraries/System.Windows.Extensions/tests/System.Windows.Extensions.Tests.csproj`,
            ],
        },
        // DScript resolver for test execution pips.
        // Sdk.Transformers must be explicitly included because the Ninja resolver
        // disables BuildXL's in-box SDK resolver (FrontEndHostController.cs line 1326-1332).
        {
            kind: "DScript",
            modules: [
                f`sdk/Sdk.Transformers/package.config.dsc`,
                f`testing/module.config.dsc`,
            ],
        },
    ]
});
