<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == ''">
    <TargetFrameworks>net11.0-linux</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0-linux'">
    <ProjectReference Update="$(RepoRoot)src/libraries/Common/tests/TestUtilities/TestUtilities.csproj">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>