<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == ''">
    <TargetFrameworks>net11.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration/ref/Microsoft.Extensions.Configuration.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.DependencyInjection/ref/Microsoft.Extensions.DependencyInjection.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.FileProviders.Physical/ref/Microsoft.Extensions.FileProviders.Physical.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.FileSystemGlobbing/ref/Microsoft.Extensions.FileSystemGlobbing.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging/ref/Microsoft.Extensions.Logging.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.ServiceProcess.ServiceController/ref/System.ServiceProcess.ServiceController.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>