<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == ''">
    <TargetFrameworks>net11.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.Binder/src/Microsoft.Extensions.Configuration.Binder.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.CommandLine/src/Microsoft.Extensions.Configuration.CommandLine.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/src/Microsoft.Extensions.Configuration.EnvironmentVariables.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/Microsoft.Extensions.Configuration.FileExtensions.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.Json/src/Microsoft.Extensions.Configuration.Json.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/Microsoft.Extensions.Configuration.UserSecrets.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration/src/Microsoft.Extensions.Configuration.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.DependencyInjection/src/Microsoft.Extensions.DependencyInjection.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Diagnostics/src/Microsoft.Extensions.Diagnostics.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Microsoft.Extensions.FileProviders.Physical.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Microsoft.Extensions.FileSystemGlobbing.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.Configuration/src/Microsoft.Extensions.Logging.Configuration.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.Console/src/Microsoft.Extensions.Logging.Console.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.Debug/src/Microsoft.Extensions.Logging.Debug.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.EventLog/src/Microsoft.Extensions.Logging.EventLog.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.EventSource/src/Microsoft.Extensions.Logging.EventSource.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging/src/Microsoft.Extensions.Logging.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Options.ConfigurationExtensions/src/Microsoft.Extensions.Options.ConfigurationExtensions.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>