<Project>

  <Target Name="ExecuteBuildTargets"
          Inputs="%(ProjectToBuild.BuildStep)"
          Outputs="unused"
          DependsOnTargets="InitializeSolutionBuildInputs">
    <Message Text="Executing Arcade build step %(ProjectToBuild.BuildStep)" Importance="low" />
    <MSBuild Projects="@(ProjectToBuild)"
             Properties="@(_SolutionBuildProps);__BuildPhase=SolutionBuild"
             RemoveProperties="$(_RemoveProps)"
             Targets="@(_SolutionBuildTargets)"
             BuildInParallel="%(ProjectToBuild.BuildInParallel)" />
  </Target>

</Project>
