<Project>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Options/gen/Microsoft.Extensions.Options.SourceGeneration.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=netstandard2.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Text.Json/gen/System.Text.Json.SourceGeneration.Roslyn4.4.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=netstandard2.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Text.RegularExpressions/gen/System.Text.RegularExpressions.Generator.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=netstandard2.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>