<Project>
  <Import Project="$(MSBuildThisFileDirectory)projectReferenceTasks.targets" />

  <PropertyGroup>
    <ProjectReferenceReplayTargets Condition="'$(ProjectReferenceReplayTargets)' == ''">$([MSBuild]::NormalizePath('$(ArtifactsObjDir)', 'static-graph', 'project-references.replay.targets'))</ProjectReferenceReplayTargets>
  </PropertyGroup>

  <Target Name="GenerateProjectReferenceReplay"
          Condition="'$(CaptureProjectReferencesFile)' != '' and '$(ProjectReferenceReplayTargets)' != ''">
    <Microsoft.DotNet.Runtime.Tasks.GenerateProjectReferenceReplay RawSelectionFile="$(CaptureProjectReferencesFile)"
                                                                  OutputFile="$(ProjectReferenceReplayTargets)" />
  </Target>
</Project>
