<Project>

  <PropertyGroup>
    <TraversalGlobalProperties>BuildAllProjects=true</TraversalGlobalProperties>
  </PropertyGroup>

  <!-- Uses the Microsoft.DotNet.Build.Tasks.TargetFramework package to filter out target frameworks from ProjectReferences. -->
  <PropertyGroup Condition="'$(FilterTraversalProjectReferences)' == 'true'">
    <BuildDependsOn>$(BuildDependsOn);ResolveP2PReferences</BuildDependsOn>
    <CleanDependsOn>$(CleanDependsOn);ResolveP2PReferences</CleanDependsOn>
    <RebuildDependsOn>$(RebuildDependsOn);ResolveP2PReferences</RebuildDependsOn>
    <TestDependsOn>$(TestDependsOn);ResolveP2PReferences</TestDependsOn>
    <VSTestDependsOn>$(VSTestDependsOn);ResolveP2PReferences</VSTestDependsOn>
    <PackDependsOn>$(PackDependsOn);ResolveP2PReferences</PackDependsOn>
    <PublishDependsOn>$(PublishDependsOn);ResolveP2PReferences</PublishDependsOn>
    <GetTargetPathDependsOn>ResolveP2PReferences</GetTargetPathDependsOn>
    <!-- Filter out ProjectReferences which aren't compatible with the project's TargetFramework. -->
    <OmitIncompatibleProjectReferences>true</OmitIncompatibleProjectReferences>
  </PropertyGroup>

  <ItemGroup Condition="'$(FilterTraversalProjectReferences)' == 'true'">
    <!-- Override the Traversal SDK setting as filtering relies on the TargetFrameworkProperties being fetched. -->
    <ProjectReference Update="@(ProjectReference)"
                      SkipGetTargetFrameworkProperties="false"  />
  </ItemGroup>

  <Target Name="Build"
          DependsOnTargets="$(BuildDependsOn)"
          Condition=" '$(IsGraphBuild)' != 'true' "
          Returns="@(CollectedBuildOutput)"
          Deferred="Item:CollectedBuildOutput:w"
          DeferredReturns="Item:CollectedBuildOutput">
    <MSBuild Projects="@(ProjectReference)"
             Condition="'%(ProjectReference.Build)' != 'false'"
             BuildInParallel="$([MSBuild]::ValueOrDefault('%(ProjectReference.BuildInParallel)', '$(BuildInParallel)'))"
             Properties="%(ProjectReference.SetConfiguration); %(ProjectReference.SetPlatform); %(ProjectReference.SetTargetFramework)"
             SkipNonexistentProjects="$(SkipNonexistentProjects)"
             SkipNonexistentTargets="$(SkipNonexistentTargets)"
             StopOnFirstFailure="$(StopOnFirstFailure)"
             Targets="%(ProjectReference.Targets)"
             ContinueOnError="$(ContinueOnError)">
      <Output TaskParameter="TargetOutputs" ItemName="CollectedBuildOutput" />
    </MSBuild>
  </Target>

  <Target Name="Rebuild"
          DependsOnTargets="$(RebuildDependsOn)"
          Condition=" '$(IsGraphBuild)' != 'true' "
          Returns="@(CollectedBuildOutput)"
          Deferred="Item:CollectedBuildOutput:r"
          DeferredReturns="Item:CollectedBuildOutput" />

  <Target Name="GetTargetPath"
          DependsOnTargets="$(GetTargetPathDependsOn)"
          Returns="@(CollectedBuildOutput)"
          Deferred="Item:CollectedBuildOutput:w"
          DeferredReturns="Item:CollectedBuildOutput">
    <MSBuild Projects="@(ProjectReference)"
             Condition="'%(ProjectReference.Build)' != 'false'"
             Targets="GetTargetPath"
             BuildInParallel="$([MSBuild]::ValueOrDefault('%(ProjectReference.BuildInParallel)', '$(BuildInParallel)'))"
             SkipNonexistentProjects="$(SkipNonexistentProjects)"
             SkipNonexistentTargets="$(SkipNonexistentTargets)"
             StopOnFirstFailure="$(StopOnFirstFailure)"
             Properties="%(ProjectReference.SetConfiguration); %(ProjectReference.SetPlatform); %(ProjectReference.SetTargetFramework)"
             ContinueOnError="$(ContinueOnError)">
      <Output TaskParameter="TargetOutputs" ItemName="CollectedBuildOutput" />
    </MSBuild>
  </Target>

</Project>
