<Project>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0-linux'">
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.CSharp/src/Microsoft.CSharp.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/Microsoft.Extensions.Configuration.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/Microsoft.Extensions.DependencyInjection.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Diagnostics.Abstractions/src/Microsoft.Extensions.Diagnostics.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.FileProviders.Abstractions/src/Microsoft.Extensions.FileProviders.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/Microsoft.Extensions.Hosting.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Logging.Abstractions/src/Microsoft.Extensions.Logging.Abstractions.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Options/src/Microsoft.Extensions.Options.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Extensions.Primitives/src/Microsoft.Extensions.Primitives.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.VisualBasic.Core/src/Microsoft.VisualBasic.Core.vbproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Collections.Immutable/src/System.Collections.Immutable.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Console/src/System.Console.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.FileVersionInfo/src/System.Diagnostics.FileVersionInfo.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.Process/src/System.Diagnostics.Process.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Drawing.Primitives/src/System.Drawing.Primitives.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Formats.Asn1/src/System.Formats.Asn1.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Formats.Tar/src/System.Formats.Tar.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Compression.Brotli/src/System.IO.Compression.Brotli.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Compression.ZipFile/src/System.IO.Compression.ZipFile.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Compression/src/System.IO.Compression.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.FileSystem.AccessControl/src/System.IO.FileSystem.AccessControl.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.FileSystem.DriveInfo/src/System.IO.FileSystem.DriveInfo.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.FileSystem.Watcher/src/System.IO.FileSystem.Watcher.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.IsolatedStorage/src/System.IO.IsolatedStorage.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.MemoryMappedFiles/src/System.IO.MemoryMappedFiles.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Pipelines/src/System.IO.Pipelines.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Pipes.AccessControl/src/System.IO.Pipes.AccessControl.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.IO.Pipes/src/System.IO.Pipes.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Linq.AsyncEnumerable/src/System.Linq.AsyncEnumerable.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Http.Json/src/System.Net.Http.Json.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Http/src/System.Net.Http.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.HttpListener/src/System.Net.HttpListener.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Mail/src/System.Net.Mail.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.NameResolution/src/System.Net.NameResolution.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Ping/src/System.Net.Ping.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Primitives/src/System.Net.Primitives.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Quic/src/System.Net.Quic.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Requests/src/System.Net.Requests.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Security/src/System.Net.Security.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-linux</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.ServerSentEvents/src/System.Net.ServerSentEvents.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.WebClient/src/System.Net.WebClient.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.WebProxy/src/System.Net.WebProxy.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.WebSockets.Client/src/System.Net.WebSockets.Client.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.WebSockets/src/System.Net.WebSockets.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Private.Xml/src/System.Private.Xml.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Reflection.Metadata/src/System.Reflection.Metadata.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Runtime.InteropServices.JavaScript/src/System.Runtime.InteropServices.JavaScript.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.AccessControl/src/System.Security.AccessControl.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0-unix</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Text.Encoding.CodePages/src/System.Text.Encoding.CodePages.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Text.Encodings.Web/src/System.Text.Encodings.Web.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Text.Json/src/System.Text.Json.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Threading.AccessControl/src/System.Threading.AccessControl.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Threading.Channels/src/System.Threading.Channels.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Threading.Tasks.Dataflow/src/System.Threading.Tasks.Dataflow.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Transactions.Local/src/System.Transactions.Local.csproj">
      <ProjectReferenceReplaySetTargetFramework>TargetFramework=net11.0</ProjectReferenceReplaySetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>