<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <UsingTask
      AssemblyFile="$(MSBuildThisFileDirectory)..\_content\tasks\netfx\xunit.v3.msbuildtasks.dll"
      Condition=" '$(MSBuildRuntimeType)' != 'Core' "
      TaskName="Xunit.v3.MSBuildTasks.XunitGenerateEntryPoint"/>
  <UsingTask
      AssemblyFile="$(MSBuildThisFileDirectory)..\_content\tasks\netcore\xunit.v3.msbuildtasks.dll"
      Condition=" '$(MSBuildRuntimeType)' == 'Core' "
      TaskName="Xunit.v3.MSBuildTasks.XunitGenerateEntryPoint"/>

  <Target Name="_XunitValidateBuild" BeforeTargets="BeforeBuild" Condition=" '$(TargetFramework)' != '' ">
    <Error Text="xUnit.net v3 test projects must be executable (set project property '&lt;OutputType&gt;Exe&lt;/OutputType&gt;'). If this is not a test project, reference xunit.v3.extensibility.core instead." Condition=" '$(OutputType)' != 'Exe' " />
    <Error Text="xUnit.net v3 test projects must build an app host (set project property '&lt;UseAppHost&gt;true&lt;/UseAppHost&gt;'). If this is not a test project, reference xunit.v3.extensibility.core instead." Condition=" '$(UseAppHost)' != 'true' AND '$(TargetFrameworkIdentifier)' == '.NETCoreApp' " />
    <Error Text="xUnit.net v3 Native AOT only supports C# at this time" Condition=" $(MSBuildThisFileName.Contains('.aot')) AND '$(Language)' != 'C#' " />
  </Target>

  <PropertyGroup Condition=" !$(MSBuildThisFileName.Contains('.aot')) ">
    <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
  </PropertyGroup>

  <Choose>
    <When Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
      <PropertyGroup>
        <AutoGenerateBindingRedirects Condition=" '$(AutoGenerateBindingRedirects)' == '' ">true</AutoGenerateBindingRedirects>
        <DebugType Condition=" '$(DebugType)' == '' ">full</DebugType>
        <GenerateBindingRedirectsOutputType Condition=" '$(GenerateBindingRedirectsOutputType)' == '' ">true</GenerateBindingRedirectsOutputType>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <DebugType Condition=" '$(DebugType)' == '' ">portable</DebugType>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup>
    <_XunitMSBuildProjectFullPath>$(MSBuildProjectFullPath)</_XunitMSBuildProjectFullPath>
    <_XunitEntryPointCachePath>$(IntermediateOutputPath)$(MSBuildProjectName).xUnit.v3.EntryPoint.cache</_XunitEntryPointCachePath>
    <_XunitEntryPointCachePath>$([MSBuild]::NormalizePath($(MSBuildProjectDirectory), $(_XunitEntryPointCachePath)))</_XunitEntryPointCachePath>
    <_XunitDeferredEntryPointCachePath>$(_XunitEntryPointCachePath)</_XunitDeferredEntryPointCachePath>
    <_XunitEntryPointFileName>XunitAutoGeneratedEntryPoint$(DefaultLanguageSourceExtension)</_XunitEntryPointFileName>
    <_XunitEntryPointPath>$([System.IO.Path]::Combine($(IntermediateOutputPath),$(_XunitEntryPointFileName)))</_XunitEntryPointPath>
    <_XunitEntryPointPath>$([MSBuild]::NormalizePath($(MSBuildProjectDirectory), $(_XunitEntryPointPath)))</_XunitEntryPointPath>
    <_XunitDeferredEntryPointPath>$(_XunitEntryPointPath)</_XunitDeferredEntryPointPath>
  </PropertyGroup>

  <Target Name="_XunitCreateEntryPointCache"
          Deferred="Item:_XunitCoreNuspec:w;Item:_XunitCoreNuspec:r;Item:_XunitEntryPointCacheHashItems:w;Item:_XunitEntryPointCacheHashItems:r;Item:XunitEntryPointCachePath:w;Item:FileWrites:w;Property:RootNamespace:r;Property:_XunitMSBuildProjectFullPath:r;Property:_XunitDeferredEntryPointCachePath:r;Property:Language:r;Property:UseMicrosoftTestingPlatformRunner:r;Property:XunitAutoGeneratedEntryPoint:r;Property:_XunitEntryPointCacheHash:w">
    <ItemGroup>
      <_XunitCoreNuspecFile Include="$(MSBuildThisFileDirectory)..\*.nuspec" />
    </ItemGroup>
    <ReadLinesFromFile PrecomputationMode="Dynamic" File="@(_XunitCoreNuspecFile)">
      <Output TaskParameter="Lines" ItemName="_XunitCoreNuspec" />
    </ReadLinesFromFile>
    <ItemGroup>
      <_XunitEntryPointCacheHashItems Deferred="true" Include="$(RootNamespace)"/>
      <_XunitEntryPointCacheHashItems Deferred="true" Include="$(_XunitMSBuildProjectFullPath)"/>
      <_XunitEntryPointCacheHashItems Deferred="true" Include="$(Language)"/>
      <_XunitEntryPointCacheHashItems Deferred="true" Include="$(UseMicrosoftTestingPlatformRunner)" />
      <_XunitEntryPointCacheHashItems Deferred="true" Include="$(XunitAutoGeneratedEntryPoint)"/>
      <_XunitEntryPointCacheHashItems Deferred="true" Include="@(_XunitCoreNuspec)" />
      <XunitEntryPointCachePath Include="$(_XunitDeferredEntryPointCachePath)" />
    </ItemGroup>
    <Hash PrecomputationMode="Dynamic" ItemsToHash="@(_XunitEntryPointCacheHashItems)">
      <Output TaskParameter="HashResult" PropertyName="_XunitEntryPointCacheHash" />
    </Hash>
    <WriteLinesToFile PrecomputationMode="Dynamic"
                      PrecomputeOutputs="$(_XunitEntryPointCachePath)"
                      Lines="$(_XunitEntryPointCacheHash)"
                      File="$(_XunitDeferredEntryPointCachePath)"
                      Overwrite="true"
                      WriteOnlyWhenDifferent="true" />
    <ItemGroup>
      <FileWrites Include="$(_XunitDeferredEntryPointCachePath)" />
    </ItemGroup>
  </Target>

  <Target
      Name="_XunitGenerateEntryPoint"
      Inputs="$(_XunitEntryPointCachePath)"
      Outputs="$(_XunitEntryPointPath)"
      Condition=" '$(XunitAutoGeneratedEntryPoint)' != 'false' "
      DependsOnTargets="_XunitCreateEntryPointCache"
      Deferred="Item:XunitEntryPointCachePath:r;Item:FileWrites:w;Property:RootNamespace:r;Property:_XunitMSBuildProjectFullPath:r;Property:_XunitDeferredEntryPointPath:r;Property:Language:r;Property:UseMicrosoftTestingPlatformRunner:r">
    <XunitGenerateEntryPoint
        SourcePath="$(_XunitDeferredEntryPointPath)"
        RootNamespace="$(RootNamespace)"
        SuffixSeed="$(_XunitMSBuildProjectFullPath)"
        Language="$(Language)"
        UseMicrosoftTestingPlatformRunner="$(UseMicrosoftTestingPlatformRunner)" />
    <ItemGroup>
      <FileWrites Include="$(_XunitDeferredEntryPointPath)" />
    </ItemGroup>
  </Target>

  <Target Name="_XunitAttachSourceFiles" BeforeTargets="BeforeCompile;CoreCompile;XamlPreCompile" DependsOnTargets="_XunitGenerateEntryPoint">
    <ItemGroup Condition=" '$(XunitRegisterBuiltInRunnerReporters)' != 'false' ">
      <Compile Include="$(MSBuildThisFileDirectory)..\_content\DefaultRunnerReporters$(DefaultLanguageSourceExtension)" />
    </ItemGroup>

    <ItemGroup Condition=" '$(XunitRegisterBuiltInResultWriters)' != 'false' ">
      <Compile Include="$(MSBuildThisFileDirectory)..\_content\DefaultResultWriters$(DefaultLanguageSourceExtension)" />
    </ItemGroup>

    <ItemGroup Condition=" '$(XunitAutoGeneratedEntryPoint)' != 'false' ">
      <CompileAfter Include="$(_XunitEntryPointPath)" Condition=" '$(Language)' == 'F#' " />
      <Compile Include="$(_XunitEntryPointPath)" Condition=" '$(Language)' != 'F#' " />
      <FileWrites Include="$(_XunitEntryPointPath)" />
    </ItemGroup>
  </Target>

  <Target Name="_XunitCopyRunnerDependencies" AfterTargets="Build" Condition=" !$(MSBuildThisFileName.Contains('.aot')) ">
    <ItemGroup>
      <XunitRunnerDependencies Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' " Include="$(MSBuildThisFileDirectory)..\_content\runners\netfx\*" />
      <XunitRunnerDependencies Condition=" '$(TargetFrameworkIdentifier)' == '.NETCoreApp' "   Include="$(MSBuildThisFileDirectory)..\_content\runners\netcore\*" />
    </ItemGroup>
    <Copy SourceFiles="@(XunitRunnerDependencies)" DestinationFolder="$([System.IO.Path]::Combine($(MSBuildProjectDirectory),$(OutputPath)))" SkipUnchangedFiles="true" />
  </Target>

</Project>
