<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <ProjectReference Include="$(RepoRoot)src/libraries/System.Runtime.Loader/tests/MissingDependency.Mid/MissingDependency.Mid.csproj" />
  </ItemGroup>
</Project>