<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <IsShipping>false</IsShipping>
    <UseDefaultTestHost>true</UseDefaultTestHost>
    <IncludeRemoteExecutor>true</IncludeRemoteExecutor>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.RemoteExecutor" Version="$(MicrosoftDotNetRemoteExecutorVersion)" />
    <PackageReference Include="Microsoft.DotNet.XUnitExtensions" Version="$(MicrosoftDotNetXUnitExtensionsVersion)" />
    <ProjectReference Include="../Microsoft.NET.Build.Caching/Microsoft.NET.Build.Caching.csproj" />
  </ItemGroup>
</Project>
