<Project>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0-linux'">
    <ProjectReference Remove="$(RepoRoot)src/libraries/Microsoft.Win32.Registry.AccessControl/tests/Microsoft.Win32.Registry.AccessControl.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/Microsoft.Win32.Registry/tests/Microsoft.Win32.Registry.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/Microsoft.Win32.SystemEvents/tests/Microsoft.Win32.SystemEvents.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Data.OleDb/tests/System.Data.OleDb.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Diagnostics.EventLog/tests/System.Diagnostics.EventLog.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Diagnostics.PerformanceCounter/tests/System.Diagnostics.PerformanceCounter.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.DirectoryServices.AccountManagement/tests/System.DirectoryServices.AccountManagement.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.DirectoryServices/tests/System.DirectoryServices.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.IO.FileSystem.AccessControl/tests/System.IO.FileSystem.AccessControl.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.IO.Pipes.AccessControl/tests/System.IO.Pipes.AccessControl.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Management/tests/System.Management.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/System.Net.Http.WinHttpHandler.Functional.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Net.Http.WinHttpHandler/tests/UnitTests/System.Net.Http.WinHttpHandler.Unit.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Net.WebSockets.Client/tests/wasm/System.Net.WebSockets.Client.Wasm.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime.InteropServices.JavaScript/tests/System.Runtime.InteropServices.JavaScript.UnitTests/System.Runtime.InteropServices.JavaScript.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Calendars.Tests/Hybrid/System.Globalization.Calendars.IOS.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Extensions.Tests/Hybrid/System.Globalization.Extensions.iOS.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Extensions.Tests/NlsTests/System.Globalization.Extensions.Nls.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Tests/Hybrid/AppleHybrid.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Tests/Hybrid/System.Globalization.IOS.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Globalization.Tests/NlsTests/System.Globalization.Nls.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Runtime.Tests/Hybrid/System.Runtime.IOS.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Runtime/tests/System.Runtime.Tests/NlsTests/System.Runtime.Nls.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Security.AccessControl/tests/System.Security.AccessControl.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Security.Cryptography.Cng/tests/System.Security.Cryptography.Cng.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Security.Permissions/tests/System.Security.Permissions.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Security.Principal.Windows/tests/System.Security.Principal.Windows.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Speech/tests/System.Speech.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Threading.AccessControl/tests/System.Threading.AccessControl.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Threading.ThreadPool/tests/WindowsThreadPool/System.Threading.ThreadPool.WindowsThreadPool.Tests.csproj" />
    <ProjectReference Remove="$(RepoRoot)src/libraries/System.Windows.Extensions/tests/System.Windows.Extensions.Tests.csproj" />
  </ItemGroup>
</Project>