<Project>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0-linux'">
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Requests/src/System.Net.Requests.csproj">
      <SetTargetFramework>TargetFramework=net11.0-unix</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>