<Project>
  <PropertyGroup Condition="'$(TargetFramework)' == ''">
    <TargetFrameworks>net11.0;net11.0-linux</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Console/src/System.Console.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Primitives/src/System.Net.Primitives.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net11.0-linux'">
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Console/src/System.Console.csproj">
      <SetTargetFramework>TargetFramework=net11.0-unix</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Formats.Asn1/src/System.Formats.Asn1.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Primitives/src/System.Net.Primitives.csproj">
      <SetTargetFramework>TargetFramework=net11.0-unix</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj">
      <SetTargetFramework>TargetFramework=net11.0-unix</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj">
      <SetTargetFramework>TargetFramework=net11.0-unix</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/libraries/System.Security.Principal.Windows/src/System.Security.Principal.Windows.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Update="$(RepoRoot)src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj">
      <SetTargetFramework>TargetFramework=net11.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>